[package]
name = "etl2pcapng"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4" }
clap = { version = "4.0", features = ["derive"] }
from-to-repr = { version = "0.1", features = ["from_to_other"] }
